process_field: title
spacy_core: en_core_web_lg
pipeline:
  preprocess:
    - drop_empty
    - lowercase
    - drop_duplicate
  token_process:
    - drop_not_alpha
    - drop_stop_words
    - drop_no_vector
    - drop_character
    - drop_fully_consonants
    - drop_fully_vowels
  process:
    - count_words
