pipeline:
  preprocess:
    processor: Preprocessor
    pipes:
      - drop_empty
      - remove_punctuation
      - lowercase
      - drop_duplicate
    args:
      column: title
  token_process:
    processor: SpacyTokenizer
    pipes:
      - drop_not_alpha
      - drop_stop_words
      - drop_no_vector
      - drop_character
      - drop_fully_consonants
      - drop_fully_vowels
    args:
      spacy_core: en_core_web_lg
  process:
    processor: SpacyTokenProcessor
    pipes:
      - count_words
      - cluster_words_kmeans
    args:
      num_of_clusters: 10
      percent_threshold: 10
      training_dataset_path: 'text-categorization/data/svm_train.json'
