pipeline:
  preprocess:
    processor: Preprocessor
    pipes:
      - drop_empty
      - remove_punctuation
      - lowercase
      - drop_duplicate
    args:
      column: title
  token_process:
    processor: GensimTokenProcessor
    pipes:
      - drop_not_alpha
      - drop_stop_words
      - drop_character
      - drop_fully_consonants
      - drop_fully_vowels
      - count_tokens
      - vectorize
      - drop_no_vector
    args:
      gensim_model_path: /home/mikehoang/projects/khpi/text-categorization/dumps/GoogleNews-vectors-negative300.bin
  process:
    processor: TokenProcessor
    pipes:
      - cluster_words_kmeans
    args:
      num_of_clusters: 10
      percent_threshold: 10
      training_dataset_path: 'text-categorization/data/svm_train.json'
